# Generated by Django 4.1.1 on 2022-09-05 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accesorios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=128)),
                ('codigo', models.CharField(max_length=128)),
                ('stock_disponible', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Camperas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=128)),
                ('codigo', models.CharField(max_length=128)),
                ('stock_disponible', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Carteras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=128)),
                ('codigo', models.CharField(max_length=128)),
                ('stock_disponible', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Zapatos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=128)),
                ('codigo', models.CharField(max_length=128)),
                ('stock_disponible', models.IntegerField()),
            ],
        ),
    ]
